# -*- coding: utf-8 -*-
"""movie analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LQR1-foWIgsD-7dkoIEpxOblAlPOwyd0
"""

!pip install nltk scikit-learn pandas

import nltk
import pandas as pd

from nltk.corpus import movie_reviews
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

nltk.download('movie_reviews')

documents = []

for category in movie_reviews.categories():
    for fileid in movie_reviews.fileids(category):
        documents.append((
            " ".join(movie_reviews.words(fileid)),
            category
        ))

df = pd.DataFrame(documents, columns=["review", "sentiment"])

df.head()

df.shape

vectorizer = TfidfVectorizer(stop_words='english')

X = vectorizer.fit_transform(df['review'])

y = df['sentiment']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

model = MultinomialNB()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

print(classification_report(y_test, y_pred))

review = ["This movie is fantastic. I really enjoyed it."]

review_vector = vectorizer.transform(review)

prediction = model.predict(review_vector)

print(prediction)

review = ["Worst movie ever. Waste of time."]

review_vector = vectorizer.transform(review)

prediction = model.predict(review_vector)

print(prediction)

import pickle

pickle.dump(model, open("movie_model.pkl","wb"))

pickle.dump(vectorizer, open("vectorizer.pkl","wb"))

